package airline.reservation.system;

public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        loadingValue = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        loadingLabel = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        backgroundColor = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(0, 153, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loadingValue.setForeground(new java.awt.Color(255, 255, 255));
        loadingValue.setText("0%");
        backgroundPanel.add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Skyline Reservations");
        backgroundPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 390, 50));

        loadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        loadingLabel.setText("Loading...");
        backgroundPanel.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        loadingBar.setForeground(new java.awt.Color(255, 204, 102));
        backgroundPanel.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 660, 10));

        backgroundColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3f0a0cfb664c5e99d93bcb026cdd25f3.jpg"))); // NOI18N
        backgroundPanel.add(backgroundColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 330));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue-gradient-background-gu71dwd19no9ra2v.jpg"))); // NOI18N
        backgroundImage.setText("jLabel1");
        backgroundPanel.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundColor;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JPanel backgroundPanel;
    public javax.swing.JProgressBar loadingBar;
    public javax.swing.JLabel loadingLabel;
    public javax.swing.JLabel loadingValue;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
